# -*- coding: utf-8 -*-
"""generate_random_numbres.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftlCLgbWgBDLuJ4TkV5aSxUO296mgZFR
"""

import random
import json

# Generate 1000 random numbers between 0 and 100
data = {}
for i in range(1000):
  n = random.randint(0,100)
  try:
    data[n] +=1
  except:
    data[n] = 1

with open('data.json', 'w') as outfile:
    json.dump(data, outfile)
