# -*- coding: utf-8 -*-
"""plot_random_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VLsUgGy_M-5me7I4lH5yjffMXL_YgIUO
"""

import json
import matplotlib.pyplot as plt

# Read data
with open('data.json') as json_file:
    data = json.load(json_file)

names = list(map(int, data.keys()))
names.sort()
values = list(data.values())
  
fig = plt.figure(figsize = (20, 5))
 
# creating the bar plot
plt.bar(names, values, color ='slateblue',
        width = 0.4)
 
plt.xlabel("Numbers")
plt.ylabel("Count")
plt.title("Random Numbers")
plt.show()